apiVersion: v1
kind: Service
metadata:
  name: frontend-service # Service name
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP   # Protocol kullanilacak
      port: 80       # Service port
      targetPort: 80 # Target port
  type: ClusterIP # Service type