apiVersion: networking.k8s.io/v1
kind: Ingress # Ingress olusturulacak demektir
metadata:
  name: app-ingress # Ingress adi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # Ingress annotation
spec:
  rules:
  - host: myapp.local # Ingress host
    http:
      paths:
      - path: / # Frontend yolu
        pathType: Prefix
        backend:
          service:
            name: frontend-service # Frontend service adi
            port:
              number: 80
      - path: /api # Backend yolu
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3000 # Backend service port
